title: cybervuln framework
email: admin@cybervuln.dev
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/cybervulns"
url: "cybervuln.dev"
twitter_username: cybervuln
github_username: cybervuln

# remote_theme: b2a3e8/jekyll-theme-console

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-notion
  # - jekyll-toc


sass:
  sass_dir: _sass
  style: compressed

header_pages:
  - index.md
  - about.md
  - archive.md
  - ctf.md

style: dark # dark (default), light or hacker
listen_for_clients_preferred_style: true # false (default) or true

footer: 'follow us on <a href="https://instagram.com/xxx">instagram? </a>'
google_analytics: UA-NNNNNNNN-N

NOTION_TOKEN: NOTION_TOKEN
defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      toc: true
  # -
  #   scope:
  #     path: ""
  #     type: gists
  #   values:
  #     layout: gist

    
notion:
  fetch_on_watch: true
  cache: false
  databases:
    - id: 63dbdd02b59546c7a4906c9ad2243fd4
      collections: posts
      filter: { "property": "Published", "checkbox": { "equals": true } }
      sorts: [{ "timestamp": "created_time", "direction": "ascending" }]

