title: cybervuln framework
email: admin@cybervuln.dev
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "cybervuln.dev"
twitter_username: cybervuln
github_username: cybervuln

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-notion


header_pages:
  - index.md
  - about.md
  - /v1/archive.md
  - /v1/ctf.md

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      toc: true


notion:
  fetch_on_watch: true
  cache: false
  databases:
    - id: 63dbdd02b59546c7a4906c9ad2243fd4
      collections: posts
      filter: { "property": "Published", "checkbox": { "equals": true } }
      sorts: [{ "timestamp": "created_time", "direction": "ascending" }]


style: dark # dark (default), light or hacker
listen_for_clients_preferred_style: true # false (default) or true

footer: 'follow us on <a href="https://instagram.com/xxx">instagram? </a>'
google_analytics: UA-NNNNNNNN-N

